# Name of your application. Used to uniquely configure containers.
service: votemosbien

# Name of the container image.
image: ccastillop/votemosbien

# Deploy to these servers.
servers:
  web:
    hosts:
      - 192.168.0.10
  jobs:
    hosts:
      - 192.168.0.10
    cmd: bundle exec backburner -q default:2,mailers:1

# Credentials for your image host.
registry:
  server: ghcr.io
  username: ccastillop
  password:
    - KAMAL_REGISTRY_PASSWORD

# Use accessory services.
accessories:
  db:
    image: postgres:14
    host: 192.168.0.10
    env:
      clear:
        POSTGRES_USER: votemosbien
        POSTGRES_DB: votemosbien_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    host: 192.168.0.10
    directories:
      - data:/data

  memcached:
    image: memcached:1.6.24
    host: 192.168.0.10
    directories:
      - data:/data

  beanstalkd:
    image: rayyounghong/beanstalkd
    host: 192.168.0.10
    directories:
      - data:/data

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    RAILS_LOG_LEVEL: info
    RAILS_SERVE_STATIC_FILES: true
    POSTGRES_HOST: votemosbien-db
    REDIS_URL: redis://votemosbien-redis:6379/1
    BEANSTALK_URL: votemosbien-beanstalkd
    MEMCACHE_SERVERS: votemosbien-memcached
    TZ: America/Lima

builder:
  arch: arm64
  remote: ssh://root@192.168.0.10

proxy:
  ssl: false
  host: votemosbien.softwarebajodemanda.com
  app_port: 3000

asset_path: /rails/public/assets

volumes:
  - "storage_votemosbien:/rails/storage/"
